### ISSUE TITLE
T4SS-type DEF files missing?

### ISSUE THREAD

**Issue by lguy** [gem-pasteur/Macsyfinder_models#2] opened 2017-11-08 14:06 UTC
I'm trying to run macsyfinder to identify T4SS systems. I've run a few tests using the Galaxy service at Pasteur, and now wants to run the standalone version. I noticed that several models available in Galaxy are not available from Macsyfinder_models. Namely, the T4SS-typeB, C, F, G, I and T are not represented by an xml file in the DEF folder. Trying to run the pT4SSi model returns an error because it cannot identify the system_ref T4SS_typeI definition.

I tried to access the toolshed associated with Pasteur's Galaxy, but without success, it seems it is down. Finally, I also tried to download the models from the Supplementary material provided with Abby et al (Sci Rep 2016) but the link there is broken as well. 

Any help appreciated at this point!

**Comment by jeanrjc** [comment] 2017-11-08 15:11
Hello,

Thanks you for you question. There are few thing we need to make clearer in the doc since things have changed lately.

Depending on whether you want to look for T4SS for conjugation or protein secretion, you will not use the same module:

- The **CONJScan** module allows the detection of all T4SS systems associated with conjugation
- The **TXSScan** module allows the detection of protein secretion systems. In the case of T4SS, only type I and type T are known to be associated with protein secretion systems. Here you are right, there is an error in the pT4SSi and pT4SSt `DEF` because the `system_ref` has been removed erroneously. Type B, C, F, G shouldn't be on Galaxy in the TXSScan module (@bneron @odoppelt)

So, if you need to look for conjugative systems, go for the CONJScan module. If you want to look for protein secretion system using the T4SS, just wait a bit, until I resolve the issue you raised. 

Best
Jean

**Comment by jeanrjc** [comment] 2017-11-08 15:39
@lguy It should be fixed now. 

Let me know if you still encounter problems.

**Comment by lguy** [comment] 2017-11-08 15:55
Hi Jean,
Thanks for your quick answer. I should have started by saying that macsyfinder and attached models are great tools and incredibly useful in finding ones way in the secretion system jungle. 

I'm indeed interested in the protein secretion systems, type I in that particular case. I'll wait until you solve the issue.

I appreciate the amount of work that it would represent, but having a tad more information about each profile would greatly help orienting oneself in selecting the right profile for the right tool. For example, I have a hard time telling the difference between pT4SSi and T4SS-typeI.

**Comment by lguy** [comment] 2017-11-08 16:06
Hi again,

I replied without seeing your comment. It works now, thanks for the very quick fix.

One small thing though (took me a few minutes to realize my mistake): in README.md for the TXSS module, the example suggests using:
`--profile-suffix .HMM`
whereas the actual suffix is .hmm.

**Comment by jeanrjc** [comment] 2017-11-08 16:09
`T4SS_typeI` does not exist anymore in `TXSScan`, and was the cause of the error you saw before.
`CONJScan` was intertwined within `TXSScan` before.

`T4SS_typeI` used to refer to the type I conjugative system (now in the separate module `CONJScan` and named `typeI`), while `pT4SSi` refers to the protein secretion system exapted from the type I secretion system. 

Another source of confusion comes from the fact that Galaxy is not up to date is these definitions, but I'm not able to change that myself.

I'll fix the `.hmm` thing, thanks.

**Closed** 2017-11-08 16:11 UTC
